# Generated by Django 3.2 on 2023-02-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_partnersurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmail',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmail',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
